### ISSUE TITLE
使用npm run build后，图片资源怎么看效果

### ISSUE THREAD

**Issue by fwyjack** [sayll/ie-webpack-start#1]
在index.css样式里面加入图片路径 background: url('../../source/img/avatar.jpg'); 
打包后，提示找不到该图片，
为什么使用build命令，build目录不会生成图片assets文件夹
需要怎么操作呢？请大神指教

**Comment by sayll** [comment]
嗯，确实发现有这样的问题。过一会就会推送修复版

**Comment by sayll** [comment]
已修复！

**Comment by fwyjack** [comment]
目录是生成了，可是打包好的图片直接损坏了，不能查看和预览，
还有生成的样式中的文件，在浏览器不能正常显示，样式里面的路径 ./assets/
这样浏览器显示的路径是：build/source/css/assets/avatar-f9ffcd92.jpg 
但assets文件夹是在build目录下面。
