### ISSUE TITLE
关于引入CSS和使用哪种模块规范

### ISSUE THREAD

**Issue by jtsang4** [sayll/ie-webpack-start#12]
请问下，如果我用npm安装了bootstrap，怎么才能引入bootstrap的CSS文件呢，我试了下直接require()不行，另外还有一个问题就是，是不是因为兼容性问题只能使用AMD规范定义模块，可以使用CommonJS规范定义模块吗？

**Comment by sayll** [comment]
前者我不太清楚。没用它做过，你可以在三个地方都尝试看看，
1：source/css/index.css 通过@import引入。
2：/viwe,通过对象模块的JS引入
3：static/index.js  引入。
后者，我只知道ES6肯定不可以，CommonJS你可以尝试定义一个这个规范的模块测试一下就应该知道了。我没测试过，也就不乱说了。如有结果，请告知。谢谢。我之后再补充文档。

**Comment by jtsang4** [comment]
@sayll 试了2个小时以上，还是没解决引入css的问题……

另外CommonJS试了一下是可以的，我定义了一个这样的模块，可以直接require得到：

`module.exports = {
  m: 2,
  n: () => 5
}`

我在以下位置试了引入bootstrap的CSS文件：

1. app/html/index.html直接link引入(link[href="bootstrap/dist/css/bootstrap.css"]);
2. app/source/css/index.css用@import "bootstrap/dist/css/bootstrap.css"引入;
3. app/static/index.js使用require("bootstrap/dist/css/bootstrap.css")引入;
4. app/view/index/index.js使用require("bootstrap/dist/css/bootstrap.css")引入.

期间也试过把Bootstrap的CSS和fonts文件复制到source目录下用相对路径去引入，还是不行，改过webpack的loader.js，直接把CSS的loader写成`loader: ["style-loader", ["css-loader", option]]`也不行，会因为bootstrap.css内部引入字体文件报错。我才刚学webpack还不太会用，可以麻烦给一些指导意见吗？因为我有点不清楚怎么改才能正常引入CSS。

**Comment by sayll** [comment]
我记的很久之前有人和我谈论过使用 bootstrap 来着。后来他成功接入了。
你可以找一些相关文章看看。不也不知道这篇对头不。
https://github.com/shakacode/bootstrap-loader

**Comment by jtsang4** [comment]
@sayll 好的，谢谢你，我去看下。另外刚才补充了一下下午试的过程，麻烦看一下哈。

**Comment by sayll** [comment]
嗯，等手头的东西忙完我再回头看看。如果你有结果了，就大概阐述一下，可以让后来者参考一下。

**Comment by jtsang4** [comment]
我另写的一个脚手架解决了bootstrap引入的问题，实现方式是：

webpack.config.js:

    module: {
      rules: [
        { test: /\.css$/, use: ['style-loader', 'css-loader'] },
        { test: /\.(woff2|woff|svg|eot|ttf)$/, use: 'url-loader?limit=50000&name=[name].[ext]' }
      ]
    }

另外还有一个解决方案，使用[copy-webpack-plugin](https://www.npmjs.com/package/copy-webpack-plugin)，将bootstrap直接复制到build目录，之后在HTML模板中引用复制过去的bootstrap。

希望可以对这个问题有帮助。
