### ISSUE TITLE
组件模板

### ISSUE THREAD

**Issue by givebest** [sayll/ie-webpack-start#14]
`app/component/paging/` 为一分页组件，通过修改：`config\webpack\modules\loader.js` 里

      function cssLoader(test, loader, path = [files.viewPath, files.cssPath]) {   
为

     function cssLoader(test, loader, path = [files.viewPath, files.cssPath, files.componentPath]) {   

可解决组件中  CSS 引用图片路径不解析问题。

但不知道如何解决组件里模板文件，如：`app/component/paging/template.html`  直接引用图片 `<img src="../../source/img/pic.jpg" alt="pic">` 路径解析问题。

**Comment by sayll** [comment]
config\webpack\modules\loader.js  ： html-loader 里面添加 files.componentPath路径

**Comment by givebest** [comment]
感谢，但未能解决，有 `demo` 么

**Comment by sayll** [comment]
你可以直接将图片的部分设置为 files.appPath。这样整个app的项目目录图片处理都能被接收到了。
分的越细处理越快，不过图片什么的不算大头，没什么关系。

**Comment by givebest** [comment]
非常感谢，还是不行，我先熟悉下 `webpack` ，自己找下答案吧。

**Comment by sayll** [comment]
嗯。最近比较忙，没太多空余时间测试。如果还是不行，你可以fork项目，然后修改你的配置，我之后空下来抽时间测试。
