### ISSUE TITLE
ie8报错

### ISSUE THREAD

**Issue by naughty-ken** [sayll/ie-webpack-start#15]
直接clone的代码，本地 cnpm install,然后build，在ie8下执行build后的代码，出错。

报错信息：
SCRIPT1010: 缺少标识符
index.a3d2acf4.js (185,37)

查看代码：
__webpack_require__.e/* require.ensure */(0).then((function () {
  var foo = __webpack_require__(20);
  console.log(foo);

}).bind(null, __webpack_require__)).catch(__webpack_require__.oe);   //185行

var vm = avalon.define({
  $id: "test",
  name: "司徒正美",
  array: [11, 22, 33]
});
![qq 20170427174646](https://cloud.githubusercontent.com/assets/8108428/25478379/6c41636c-2b73-11e7-87a4-d0574ca26ce9.png)
![qq 20170427174641](https://cloud.githubusercontent.com/assets/8108428/25478385/7427aaa0-2b73-11e7-9b52-1a2faaa167d2.png)

**Comment by sayll** [comment]
不好意思，应该是webpack2 不支持 require.ensure,去掉view/index/index.js的这部分就好了。

**Comment by naughty-ken** [comment]
确实，本地试了，去除后就不报错了，正常运行了
