### ISSUE TITLE
热更新无效

### ISSUE THREAD

**Issue by XIAOGUIGUI** [sayll/ie-webpack-start#16]
昨天试用了你的项目，发现修改CSS时没有自动刷新。不知道你那里是否存在同样的问题
![2b4 tir uqo oes 2 gw](https://cloud.githubusercontent.com/assets/8243283/26663128/5dc19844-46bb-11e7-9cd9-4f27abba487a.png)

**Comment by sayll** [comment]
如果我没记错，默认导入的不开启自动刷新，除非通过js, import的css才有自动刷新的功能。

**Comment by XIAOGUIGUI** [comment]
昨天尝试了一下，如果是webpack2,使用extract-text-webpack-plugin提取css都不会自动刷新。就算是js，import的也不会。

**Comment by XIAOGUIGUI** [comment]
还有那个低版本压缩的问题，你是否有尝试过解决？发现不压缩文件相差太大了。

**Comment by sayll** [comment]
尝试过，由于版本过高，导致无法兼容IE8以下的浏览器，这个只能等日后研究低版本，退而求其次了。
