### ISSUE TITLE
网页ico图标如何添加

### ISSUE THREAD

**Issue by crazyliuzc** [sayll/ie-webpack-start#18]
如题，在页面header中添加代码
```
<link type="image/x-icon" href="../source/img/titlelogo.ico" rel="shortcut icon"/>
<link href="../source/img/titlelogo.ico" rel="bookmark icon"/>
```
图片路径无法识别；
在HtmlWebpackPlugin中添加favicon编译会报npm ERR! code ELIFECYCLE

@sayll 大神帮忙看看呗

**Comment by sayll** [comment]
通过指定一个静态资源文件夹，配合alias使用。最后通过插件复制静态资源文件到打包文件就好了。

**Comment by crazyliuzc** [comment]
@sayll 大神，能不能写个demo瞧瞧，图片打包后如何和代码
```
<link type="image/x-icon" href="../source/img/titlelogo.ico" rel="shortcut icon"/>
<link href="../source/img/titlelogo.ico" rel="bookmark icon"/>
```
中的地址对应上，如果不能对应编译会报错的

**Comment by crazyliuzc** [comment]
在HtmlWebpackPlugin中添加favicon参数，路径正确可以解决“shortcut icon”，但是“bookmark icon”不知道怎么搞

**Comment by sayll** [comment]
@crazyliuzc 为项目添加静态资源文件夹了。看文档使用手册 -> 基础篇 -> 静态资源。
