### ISSUE TITLE
多页面的如何配置？

### ISSUE THREAD

**Issue by yujiyuan** [sayll/ie-webpack-start#19]

**Comment by sayll** [comment]
请看文档->https://github.com/sayll/ie-webpack-start#%E5%9F%BA%E6%9C%AC

**Comment by yujiyuan** [comment]
![Uploading 微信图片_20171217213854.png…]()


这是我对着文档弄的，
但是打开localhost:3000还是找不到文件

**Comment by sayll** [comment]
@yujiyuan 图有问题吧

**Comment by yujiyuan** [comment]
![_20171217213854](https://user-images.githubusercontent.com/16329615/34080229-c0cd0336-e375-11e7-8e9a-bcb016066c3d.jpg) @sayll

**Comment by sayll** [comment]
@yujiyuan -> https://github.com/sayll/ie-webpack-start#%E4%BD%BF%E7%94%A8CSS%E9%A2%84%E5%A4%84%E7%90%86%E5%99%A8

**Comment by yujiyuan** [comment]
不可以同时使用css和scss吗？

**Comment by sayll** [comment]
@yujiyuan 早前没这么个需求，将没做了。

**Comment by yujiyuan** [comment]
@sayll 我把base.js里的cssType改成Scss，然后app里的样式文件也都是.scss结尾的，还是不可以。。。。

**Comment by sayll** [comment]
@yujiyuan 这类预处理依赖不内置到里面，根据自己需要添加，添加完后，css和预处理器都可直接使用。
cnpm install sass-loader node-sass

**Comment by yujiyuan** [comment]
@sayll 可以使用arttemplate.js吗？

**Comment by sayll** [comment]
@yujiyuan 第三方的，我不清楚，你自己试试就知道了。它自身支持的话，你直接用它的cdn就好了

**Comment by yujiyuan** [comment]
@sayll 好的
