### ISSUE TITLE
样式中的图片生成路径不正确，图片打包后不能正确打开

### ISSUE THREAD

**Issue by fwyjack** [sayll/ie-webpack-start#2]
目录是生成了，可是打包好的图片直接损坏了，不能查看和预览，
还有生成的样式中的文件，在浏览器不能正常显示，样式里面的路径 ./assets/
这样浏览器显示的路径是：build/source/css/assets/avatar-f9ffcd92.jpg
但assets文件夹是在build目录下面。

**Comment by sayll** [comment]
建议你重新clone本项目，我测试了，没有发现你所描述的问题。

**Comment by fwyjack** [comment]
恩，我重新clone就OK了，谢谢大神，如果遇到其它问题在来请教，不知道大神是否方便加个QQ
我的QQ:4281774
