### ISSUE TITLE
开发环境下保存代码虽然刷新页面但是修改内容并未编译刷新

### ISSUE THREAD

**Issue by BruceHong666** [sayll/ie-webpack-start#21]
### 问题
开发环境下修改完代码之后，概率出现`webpack: Compiled successfully`但是页面没刷新；
概率出现虽然页面刷新了，但是修改的代码未生效。
抠脚的解决处理，复制几十行的console.log(“XXXX”)来让内容刷新，
为什么不重启？启动过程比较慢，所以我选择了抠脚

### 环境：
- node v6.9.1
- window 10 x64
- ie-webpack-start 2.0

感谢作者为正在被低版本IE荼毒的开发人员做出的贡献

**Comment by PreciousDust** [comment]
这个问题解决了吗？我现在的问题是修改 html和 css 都不触发热更新，需要手动刷新页面

**Comment by sayll** [comment]
有计划，将在下个版本进行全面优化。

**Comment by BruceHong666** [comment]
使用ESlint 格式化工具，快速格式化后整个文件被外部修改。这样可以比较正常的刷新了 @sjiangbei
