### ISSUE TITLE
使用ane组件报错

### ISSUE THREAD

**Issue by simple890921** [sayll/ie-webpack-start#25]
组件库中有使用 import，请问有办法调整吗

**Comment by simple890921** [comment]
地址：https://blog.xxapp.io/ane/#!/select

**Comment by sayll** [comment]
文档注明了，使用 import 存在兼容问题，最好通过 其它打包工具将你使用的组件库打包为 umd,再使用

**Comment by simple890921** [comment]
> 文档注明了，使用 import 存在兼容问题，最好通过 其它打包工具将你使用的组件库打包为 umd,再使用

好的了解了。谢谢
