### ISSUE TITLE
将样式文件后缀名改成.less，build会失败

### ISSUE THREAD

**Issue by ximige** [sayll/ie-webpack-start#4]
根据文档提示修改的，less加载器也安装了

**Comment by sayll** [comment]
配置，错误信息截图呗。

**Comment by ximige** [comment]
![Uploading image.png…]()

**Comment by ximige** [comment]
build 后的错误提示
![qq 20170322164552](https://cloud.githubusercontent.com/assets/11029095/24189500/36365f12-0f20-11e7-90ff-432e681bcde3.png)

**Comment by ximige** [comment]
安装了less loader 然后修改了以下两处
![less](https://cloud.githubusercontent.com/assets/11029095/24189596/9a1f52fe-0f20-11e7-858c-5c48077c88cb.png)

**Comment by sayll** [comment]
source/css/*下面的样式修改之。就OK了

**Comment by ximige** [comment]
成功啦！！谢谢！！
