### ISSUE TITLE
html文件名带'-'会导致build失败

### ISSUE THREAD

**Issue by ximige** [sayll/ie-webpack-start#5]
在尝试多页面应用时发现，把‘-’去掉就成功了

**Comment by sayll** [comment]
![image](https://cloud.githubusercontent.com/assets/18632641/24193149/3a7f03a6-0f2c-11e7-8b92-5d3b762a3d0c.png)
不会啊。你使用最近更新的版本看看。如果还是不行，你再把错误信息和添加的文件目录告诉我。

**Comment by ximige** [comment]
嗯，重新试过，可以了
