### ISSUE TITLE
组件加载问题

### ISSUE THREAD

**Issue by ximige** [sayll/ie-webpack-start#6]
![default](https://cloud.githubusercontent.com/assets/11029095/24284513/9e155fc0-10a6-11e7-9589-370c259c1ba5.png)
要加载这种带CSS和图片的组件，应该怎么加载，目录应该怎么放置，注意事项是什么？求指点

**Comment by sayll** [comment]
重复调用的组件可以放到view里面分出一个独立的文件夹别和html内的文件名字冲突就好，图片样式表通过JS引入。

**Comment by sayll** [comment]
反正组件别放入static里面就好了，因为那个目录不支持ES6的语法，然后具体的调整看你的个人经验吧，我的意见和建议只是提供你参考。通过暴露一个入口，其他view内的文件去引用组件的入口文件就可以了。你可以通过修改配置文件，来改变目录结构，做出适合自己的。

**Comment by ximige** [comment]
好的，谢谢，我试试
