### ISSUE TITLE
带hash的字体文件加载错误

### ISSUE THREAD

**Issue by yourlin** [sayll/ie-webpack-start#7]
将字体正则表达式改成这样就可以了
`test: /\.(eot|woff|woff2|svg|ttf)([\?]?.*)$/`

**Comment by sayll** [comment]
首先感谢，你提的意见。对于一些优化的建议我会接受的。有什么好的意见和建议，可以fork项目后再将您针对该项目的优化部分pull requests,给予说明，我会将可行的pull合并到项目中的。由于本人不使用该项目，你提出的修改部分可以让其他更多的人收益。

**Comment by sayll** [comment]
还有这个应该直接调用字体文件原名称。而最后生成的打包文件会为字体文件自动生成它所需的hash值到文件名中。每次修改字体文件，它们产生的hash值也是不同的，而不应该一开始直接用带hash的文件名。

**Comment by yourlin** [comment]
主要是引入第三方组件的时候会有这个问题

**Comment by sayll** [comment]
OK，没影响到正常使用。我之后会更新的。你可以自己针对这部分做出调整先。
